### ISSUE TITLE
Zack's Questions

### ISSUE THREAD

**Issue by zwhile** [ShubyM/Final-Puzzle#3]
2 questions/clarifications:

1. Can you only see the hat of the person right before you (in guessing order), or can you see the hats of everyone who guessed before you?
1. Are any guarantees given about the distribution of the black/white hats?  E.g. guaranteed 5 black and 5 white, etc.

**Comment by ShubyM** [comment]
1. Everyone person in the line can only look at the hat colors of the people shorter than them. I should have clarified that every person in the line hears everyone else's guesses so like they know what the previous people before them guessed.
2. There is no guarantee about the number of black and white hats. Just that the sum of them is ten.

**Comment by zwhile** [comment]
One bit of confusion on my part:
> All ten of you will be placed in a single file line, facing forward, and in descending order of height from left to right (tallest person on the left and shortest person on the right).

I interpret this as every facing straight-forward at the person taller to them (to the left of them), is this accurate?  And, if that's the case, can you see anyone's hat color?  

Also, just thought of this, are we told when someone makes the first (free) mistake?

**Comment by ShubyM** [comment]
Ohhh no. I mean the tallest person is on the far left and the shortest person on the far right. So like if we thought of people with heights 1-10 they would be represented like this [10,9,8,7,6,5,4,3,2,1]. So 10 can see the hat colors of 9,8,7,6 and so on and 6 can see the hat colors of 5,4,3,2 and 1.

**Comment by zwhile** [comment]
Ah, I see, so "forward" in this case is _toward_ the shortest people (to the right)?

**Comment by ShubyM** [comment]
Yes!

**Comment by ShubyM** [comment]
Also, just to be explicit, you should remember that collectively the group is allowed to make one mistake and you are not told when this occurs.

**Comment by zwhile** [comment]
Awesome, thanks!  Sorry for the confusion haha.
